version: "3.4"

services:
   mongo:
      image: mongo
      ports:
      - 27017:27017
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: password

   api:
      image: node:alpine3.10
      ports:
         - ${API_PORT}:3000
      environment:
         PORT: ${API_PORT}
         MONGO_URL: "mongodb://root:password@mongo/app"
         DATABASE_URL: "postgres://root:password@db/app"
      volumes:
         - ./api:/home/node/api
      working_dir: /home/node/api
      command: sh -c "npm install --no-update-notifier; npm start api --no-update-notifier"

   client:
      image: node:alpine3.10
      ports:
         - ${CLIENT_PORT}:3000
      environment: {}
      volumes:
         - ./client:/home/node/app
      working_dir: /home/node/app
      command: sh -c "yarn install; yarn start"

   db:
      image: postgres:alpine
      environment:
         POSTGRES_DB: app
         POSTGRES_USER: root
         POSTGRES_PASSWORD: password
      ports:
         - 5432:5432
      volumes:
         - db-data:/var/lib/postgresql/data:rw
   adminer:
      image: 'adminer:4.7'
      ports:
            - '8081:8080'
volumes:
   db-data: {}